name: DeployFlow
on:
   push:
      branches:
         - prod
jobs:
   build-front-end:
      name: Build Front End
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses: actions/checkout@master
         - name: Install Dependencies
           run: npm ci
         - name: Build Client
           run: npm run build:prod:client
         - name: Archive Production Artifact
           uses: actions/upload-artifact@master
           with:
              name: dist-client
              path: dist/client
   build-back-end:
      name: Build Back End
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses: actions/checkout@master
         - name: Install Dependencies
           run: npm ci
         - name: Build Server
           run: npm run build:prod:server
         - name: Archive Production Artifact
           uses: actions/upload-artifact@master
           with:
              name: dist-server
              path: dist/server
   deploy-front-end:
      name: Deploy GitHub Pages Front-End
      needs: [build-front-end, build-back-end]
      runs-on: ubuntu-latest
      steps:
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist-client
              path: dist
         - name: Deploy 🚀
           uses: JamesIves/github-pages-deploy-action@3.7.1
           with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages
              FOLDER: dist
   deploy-itch-io-front-end:
      name: Deploy Itch IO Front-End
      needs: [build-front-end]
      runs-on: ubuntu-latest
      steps:
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist-client
              path: dist
         - name: Deploy 🚀
           uses: josephbmanley/butler-publish-itchio-action@master
           env:
              BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
              CHANNEL: 'html5'
              ITCH_GAME: the-big-cheese
              ITCH_USER: dolanmiu
              PACKAGE: dist
   deploy-glitch-back-end:
      name: Deploy Glitch Back-End
      needs: [build-front-end, build-back-end]
      runs-on: ubuntu-latest
      steps:
         - name: Clone Glitch Project
           run: git clone https://${{ secrets.GLITCH_GIT_TOKEN }}@api.glitch.com/git/game-off
         - name: Clear Repo
           run: find ./game-off -mindepth 1 ! -regex '^./game-off/\.git\(/.*\)?' -delete
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist-server
              path: game-off
         - name: Deploy 🚀
           run: |
              cd game-off
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Actions"
              git add .
              git commit -m "Deploying Server"
              git push
   deploy-eu-back-end:
      name: Deploy Heroku EU Back-End
      needs: [build-front-end, build-back-end]
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: akhileshns/heroku-deploy@v3.6.8
           with:
              heroku_api_key: ${{ secrets.HEROKU_API_KEY_2 }}
              heroku_app_name: 'the-big-cheese-eu'
              heroku_email: 'actions@github.com'
   deploy-us-back-end:
      name: Deploy Heroku US Back-End
      needs: [build-front-end, build-back-end, deploy-eu-back-end]
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: akhileshns/heroku-deploy@v3.6.8
           with:
              heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
              heroku_app_name: 'the-big-cheese-us'
              heroku_email: 'actions@github.com'
