name: DefaultFlow
on:
   push:
      branches:
         - dev
         - prod
   pull_request:
      branches:
         - dev
         - prod
jobs:
   build:
      name: Build
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout Repo
            uses: actions/checkout@master
         -  name: Install Dependencies
            run: npm ci
         -  name: Build Server
            run: npm run build:prod:server
         -  name: Build Client
            run: npm run build:prod:client
         -  name: Archive Production Artifact
            uses: actions/upload-artifact@master
            with:
               name: dist
               path: dist
   test:
      name: Test
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout Repo
            uses: actions/checkout@master
         -  name: Install Dependencies
            run: npm ci
         -  name: Test
            run: npm run test
   lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout Repo
            uses: actions/checkout@master
         -  name: Install Dependencies
            run: npm ci
         -  name: Lint
            run: npm run lint
   sass-lint:
      name: Sass Lint
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout Repo
            uses: actions/checkout@master
         -  name: Install Dependencies
            run: npm ci
         -  name: Sass Lint
            run: npm run sass-lint
   prettier:
      name: Prettier
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout Repo
            uses: actions/checkout@master
         -  name: Install Dependencies
            run: npm ci
         -  name: Prettier
            run: npm run prettier


# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the dev branch
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
